import type { ExportConfig, Node, Project } from "../core/schema";
import type { Pivot } from "../core/schema";

/** Unity RectTransform.pivot，与 requirements §2.12.4 一致 */
const PIVOT_UNITY: Record<Pivot, [number, number]> = {
  topLeft: [0, 1],
  topCenter: [0.5, 1],
  topRight: [1, 1],
  centerLeft: [0, 0.5],
  center: [0.5, 0.5],
  centerRight: [1, 0.5],
  bottomLeft: [0, 0],
  bottomCenter: [0.5, 0],
  bottomRight: [1, 0],
};

function csEscapeChar(c: string): string {
  if (c === "\\") {
    return "\\\\";
  }
  if (c === '"') {
    return '\\"';
  }
  if (c === "\n") {
    return "\\n";
  }
  if (c === "\r") {
    return "\\r";
  }
  return c;
}

/** 普通 C# 字符串字面量 */
export function csStringLiteral(s: string): string {
  return `"${[...s].map(csEscapeChar).join("")}"`;
}

/** verbatim 路径（Windows 友好），生成 C# 的 @"..." */
export function csVerbatimPath(p: string): string {
  return `@"${p.replace(/"/g, '""')}"`;
}

/** C# 中将路径中的反斜杠规范为斜杠：.Replace("\\", "/") */
function csharpPathNormalizeExpr(): string {
  return `.Replace(${csStringLiteral("\\")}, ${csStringLiteral("/")})`;
}

let nameCounter = 0;
function freshName(prefix: string): string {
  nameCounter += 1;
  return `${prefix}_${nameCounter}`;
}

function resetNames(): void {
  nameCounter = 0;
}

function pivotExpr(p: Pivot): string {
  const [x, y] = PIVOT_UNITY[p];
  return `new Vector2(${x}f, ${y}f)`;
}

/** 生成 Unity Editor 导入脚本（写入 .cs 后置于 Editor 文件夹执行） */
export function generateUnityScript(
  project: Project,
  exportConfig: ExportConfig,
  sourceAssetPath: string,
): string {
  resetNames();
  const u = exportConfig.unity;
  const rr = u.referenceResolution;
  const sourceLit = csVerbatimPath(sourceAssetPath);
  const assetRoot = csStringLiteral(u.assetRootPath.replace(/[/\\]+$/, ""));
  const defaultFont = csStringLiteral(u.defaultFont);
  const menuLabel = csStringLiteral(`LWB UI/导入「${project.meta.name}」`);

  const copyMethod = emitLwbCopyOneStaticMethod();
  const copyBlock = emitRunCopyAssetsBody(project, sourceLit, assetRoot);
  const treeBlock = project.nodes[0]
    ? emitNode(project, project.nodes[0], "canvasRt", 0)
    : "// 无根节点";

  return `// <auto-generated> LWB UI Editor — Unity 导入脚本
// 请勿手改生成逻辑；请从编辑器重新导出。
#if UNITY_EDITOR
using System;
using System.IO;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

namespace LwbUiGenerated {
  public static class LwbUiImport_${sanitizeMenuSuffix(project.meta.name)} {
    const string SourceProjectDir = ${sourceLit};
    const string AssetRootUnity = ${assetRoot};
    const string DefaultFontAssetPath = ${defaultFont};
    const float FontSizeScale = ${u.fontSizeScale}f;
    const float ScreenMatch = ${u.screenMatchMode}f;

${copyMethod}

    [MenuItem(${menuLabel})]
    public static void Run() {
      try {
        ${copyBlock}
        var canvas = CreateCanvas();
        var canvasRt = canvas.GetComponent<RectTransform>();
${indentLines(treeBlock, 8)}
        var prefabPath = Path.Combine(AssetRootUnity, ${csStringLiteral(safeFileName(project.meta.name) + "_LWB_UI.prefab")})${csharpPathNormalizeExpr()};
        var dir = Path.GetDirectoryName(prefabPath);
        if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir)) {
          Directory.CreateDirectory(dir);
        }
        PrefabUtility.SaveAsPrefabAsset(canvas, prefabPath);
        AssetDatabase.Refresh();
        EditorUtility.DisplayDialog("LWB UI", "已生成 Prefab：\\n" + prefabPath, "确定");
      } catch (Exception ex) {
        EditorUtility.DisplayDialog("LWB UI 导出失败", ex.Message, "确定");
        throw;
      }
    }

    static GameObject CreateCanvas() {
      var go = new GameObject(${csStringLiteral(project.meta.name + "_Canvas")});
      var c = go.AddComponent<Canvas>();
      c.renderMode = RenderMode.ScreenSpaceOverlay;
      var scaler = go.AddComponent<CanvasScaler>();
      scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
      scaler.referenceResolution = new Vector2(${rr[0]}f, ${rr[1]}f);
      scaler.screenMatchMode = CanvasScaler.ScreenMatchMode.MatchWidthOrHeight;
      scaler.matchWidthOrHeight = ScreenMatch;
      go.AddComponent<GraphicRaycaster>();
      var rt = go.GetComponent<RectTransform>();
      rt.anchorMin = Vector2.zero;
      rt.anchorMax = Vector2.one;
      rt.offsetMin = Vector2.zero;
      rt.offsetMax = Vector2.zero;
      return go;
    }

    static void LwbApplyRect(RectTransform rt, float px, float py, float w, float h, Vector2 pivot) {
      rt.anchorMin = new Vector2(0f, 1f);
      rt.anchorMax = new Vector2(0f, 1f);
      rt.pivot = pivot;
      rt.sizeDelta = new Vector2(w, h);
      rt.anchoredPosition = new Vector2(px, -py);
    }

    static Color LwbColor(string hex, float opacity) {
      if (string.IsNullOrEmpty(hex) || hex[0] != '#') return new Color(1f, 1f, 1f, opacity);
      var s = hex.Length >= 7 ? hex.Substring(1, 6) : "FFFFFF";
      byte R = Convert.ToByte(s.Substring(0, 2), 16);
      byte G = Convert.ToByte(s.Substring(2, 2), 16);
      byte B = Convert.ToByte(s.Substring(4, 2), 16);
      return new Color(R / 255f, G / 255f, B / 255f, opacity);
    }

    static TMP_FontAsset LwbLoadFont() {
      if (!string.IsNullOrEmpty(DefaultFontAssetPath)) {
        var f = AssetDatabase.LoadAssetAtPath<TMP_FontAsset>(DefaultFontAssetPath);
        if (f != null) return f;
        Debug.LogWarning("LWB UI: 未找到指定字体，将回退到 TMP 默认字体。路径: " + DefaultFontAssetPath);
      }
      var def = TMP_Settings.defaultFontAsset;
      if (def != null) return def;
      Debug.LogWarning("LWB UI: TMP 默认字体也未找到，文字可能无法显示。请检查 TMP Essentials 是否已导入。");
      return null;
    }

    static Sprite LwbLoadSprite(string assetId) {
      if (string.IsNullOrEmpty(assetId)) return null;
      var rel = LwbAssetRelPath(assetId);
      if (rel == null) return null;
      var unityPath = Path.Combine(AssetRootUnity, rel)${csharpPathNormalizeExpr()};
      var sp = AssetDatabase.LoadAssetAtPath<Sprite>(unityPath);
      if (sp != null) return sp;
      foreach (var a in AssetDatabase.LoadAllAssetsAtPath(unityPath)) {
        if (a is Sprite s) return s;
      }
      Debug.LogWarning("LWB UI: 未找到 Sprite，请检查资产路径: " + unityPath);
      return null;
    }

    static Sprite LwbMakeRoundedSprite(float radius) {
      int r = Mathf.Max(1, Mathf.RoundToInt(radius));
      var assetPath = AssetRootUnity + "/assets/rounded_r" + r + ".png";
      var existing = AssetDatabase.LoadAssetAtPath<Sprite>(assetPath);
      if (existing != null) return existing;
      int sz = r * 2 + 2;
      var tex = new Texture2D(sz, sz, TextureFormat.RGBA32, false);
      var px = new Color32[sz * sz];
      float threshold = (r + 0.5f) * (r + 0.5f);
      for (int y = 0; y < sz; y++) {
        for (int x = 0; x < sz; x++) {
          float nx = x < r ? r - x : (x > r ? x - r - 1 : 0);
          float ny = y < r ? r - y : (y > r ? y - r - 1 : 0);
          px[y * sz + x] = nx * nx + ny * ny <= threshold
            ? new Color32(255, 255, 255, 255) : default;
        }
      }
      tex.SetPixels32(px);
      tex.Apply();
      var projectRoot = Path.GetDirectoryName(Application.dataPath);
      var absPath = Path.GetFullPath(Path.Combine(projectRoot, assetPath));
      var absDir = Path.GetDirectoryName(absPath);
      if (!string.IsNullOrEmpty(absDir) && !Directory.Exists(absDir)) Directory.CreateDirectory(absDir);
      File.WriteAllBytes(absPath, tex.EncodeToPNG());
      UnityEngine.Object.DestroyImmediate(tex);
      AssetDatabase.ImportAsset(assetPath);
      var ti = AssetImporter.GetAtPath(assetPath) as TextureImporter;
      if (ti != null) {
        ti.textureType = TextureImporterType.Sprite;
        ti.spriteImportMode = SpriteImportMode.Single;
        ti.spriteBorder = new Vector4(r, r, r, r);
        ti.SaveAndReimport();
      }
      var sp = AssetDatabase.LoadAssetAtPath<Sprite>(assetPath);
      if (sp == null) Debug.LogWarning("LWB UI: 未能加载圆角 Sprite: " + assetPath);
      return sp;
    }

    static string LwbAssetRelPath(string assetId) {
      ${emitAssetIdToRelPathTable(project)}
    }
  }
}
#endif
`;
}

function sanitizeMenuSuffix(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_").slice(0, 40) || "Project";
}

function safeFileName(name: string): string {
  return name.replace(/[/\\\\?%*:|"<>]/g, "_").trim() || "UI";
}

function indentLines(s: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return s
    .split("\n")
    .map((l) => (l.length ? pad + l : l))
    .join("\n");
}

function emitLwbCopyOneStaticMethod(): string {
  return `    static void LwbCopyOne(string srcRoot, string dstRoot, string rel) {
      var from = Path.GetFullPath(Path.Combine(srcRoot, rel));
      var to   = Path.GetFullPath(Path.Combine(dstRoot, rel));
      var dir  = Path.GetDirectoryName(to);
      if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir)) Directory.CreateDirectory(dir);
      if (!File.Exists(from)) {
        Debug.LogWarning("LWB UI: 资产文件未找到，已跳过: " + from);
        return;
      }
      File.Copy(from, to, true);
    }`;
}

function emitRunCopyAssetsBody(project: Project, sourceAbsExpr: string, _assetRootExpr: string): string {
  const lines: string[] = [
    `var _srcAssetsDir = Path.GetFullPath(Path.Combine(SourceProjectDir, "assets"));`,
    `if (!Directory.Exists(_srcAssetsDir)) {`,
    `  throw new DirectoryNotFoundException("找不到项目 assets 目录: " + _srcAssetsDir);`,
    `}`,
    `var _projectRoot  = Path.GetDirectoryName(Application.dataPath);`,
    `var _assetRootAbs = Path.GetFullPath(Path.Combine(_projectRoot, AssetRootUnity));`,
    `if (!Directory.Exists(_assetRootAbs)) {`,
    `  Directory.CreateDirectory(_assetRootAbs);`,
    `}`,
  ];
  for (const a of project.assets) {
    const rel = a.path.replace(/^[/\\]+/, "").replace(/\\/g, "/");
    lines.push(`LwbCopyOne(${sourceAbsExpr}, _assetRootAbs, ${csStringLiteral(rel)});`);
  }
  lines.push(`AssetDatabase.Refresh();`);
  lines.push(
    `foreach (var guid in AssetDatabase.FindAssets("t:Texture2D", new[] { AssetRootUnity })) {`,
    `  var p = AssetDatabase.GUIDToAssetPath(guid);`,
    `  if (!p.EndsWith(".png", StringComparison.OrdinalIgnoreCase)) continue;`,
    `  var ti = AssetImporter.GetAtPath(p) as TextureImporter;`,
    `  if (ti != null) {`,
    `    ti.textureType = TextureImporterType.Sprite;`,
    `    ti.spriteImportMode = SpriteImportMode.Single;`,
    `    ti.SaveAndReimport();`,
    `  }`,
    `}`,
  );
  return lines.join("\n        ");
}

function emitAssetIdToRelPathTable(project: Project): string {
  const cases = project.assets.map(
    (a) =>
      `        case ${csStringLiteral(a.id)}: return ${csStringLiteral(a.path.replace(/^[/\\]+/, "").replace(/\\/g, "/"))};`,
  );
  return [`      switch (assetId) {`, ...cases, `        default: return null;`, `      }`].join("\n");
}

function emitNode(project: Project, node: Node, parentRtVar: string, indent: number): string {
  const pad = " ".repeat(indent);
  const goVar = freshName("go");
  const rtVar = freshName("rt");
  const lines: string[] = [];

  lines.push(`${pad}var ${goVar} = new GameObject(${csStringLiteral(node.name)});`);
  lines.push(`${pad}${goVar}.transform.SetParent(${parentRtVar}, false);`);
  lines.push(`${pad}var ${rtVar} = ${goVar}.AddComponent<RectTransform>();`);
  lines.push(
    `${pad}LwbApplyRect(${rtVar}, ${node.x}f, ${node.y}f, ${node.width}f, ${node.height}f, ${pivotExpr(node.pivot)});`,
  );

  if (!node.visible) {
    lines.push(`${pad}${goVar}.SetActive(false);`);
  }

  const op = node.opacity;

  switch (node.type) {
    case "panel": {
      lines.push(...emitPanel(node, goVar, op, pad));
      for (const c of node.children) {
        lines.push(emitNode(project, c, `${rtVar}`, indent + 2));
      }
      break;
    }
    case "image": {
      lines.push(...emitImage(node, goVar, op, pad));
      break;
    }
    case "text": {
      lines.push(...emitText(node, goVar, op, pad));
      break;
    }
    case "button": {
      lines.push(...emitButton(node, goVar, op, pad));
      for (const c of node.children) {
        lines.push(emitNode(project, c, `${rtVar}`, indent + 2));
      }
      break;
    }
    case "slider": {
      lines.push(...emitSlider(node, goVar, rtVar, pad));
      break;
    }
    case "toggle": {
      lines.push(...emitToggle(node, goVar, rtVar, op, pad));
      break;
    }
    case "inputField": {
      lines.push(...emitInputField(node, goVar, rtVar, op, pad));
      break;
    }
    default:
      break;
  }

  return lines.join("\n");
}

function emitPanel(
  node: Extract<Node, { type: "panel" }>,
  goVar: string,
  opacity: number,
  pad: string,
): string[] {
  const lines: string[] = [];
  const bg = node.background;
  if (!bg) return lines;

  const radius = node.borderRadius ?? 0;
  const bgOpacity = bg.bgOpacity ?? 1.0;
  const alpha = +Math.min(1, Math.max(0, opacity * bgOpacity)).toFixed(4);
  const tint = bg.tint ?? "#FFFFFF";

  lines.push(`${pad}{`);
  lines.push(`${pad}  var img = ${goVar}.AddComponent<Image>();`);

  if (bg.assetId) {
    lines.push(`${pad}  var sp = LwbLoadSprite(${csStringLiteral(bg.assetId)});`);
    lines.push(`${pad}  if (sp != null) img.sprite = sp;`);
    if (radius > 0) {
      lines.push(`${pad}  // Note: borderRadius=${radius} not clipped for image backgrounds`);
    }
  } else {
    // 纯色背景：radius>0 时用程序化圆角贴图做 9-slice
    if (radius > 0) {
      lines.push(`${pad}  img.sprite = LwbMakeRoundedSprite(${radius}f);`);
      lines.push(`${pad}  img.type = Image.Type.Sliced;`);
    }
  }

  lines.push(`${pad}  img.color = LwbColor(${csStringLiteral(tint)}, ${alpha}f);`);
  lines.push(`${pad}}`);
  return lines;
}

function emitImage(
  node: Extract<Node, { type: "image" }>,
  goVar: string,
  opacity: number,
  pad: string,
): string[] {
  const lines: string[] = [];
  lines.push(`${pad}{`);
  lines.push(`${pad}  var img = ${goVar}.AddComponent<Image>();`);
  if (node.assetId) {
    lines.push(`${pad}  var sp = LwbLoadSprite(${csStringLiteral(node.assetId)});`);
    lines.push(`${pad}  if (sp != null) img.sprite = sp;`);
  }
  lines.push(`${pad}  img.color = LwbColor(${csStringLiteral(node.tint ?? "#FFFFFF")}, ${opacity}f);`);
  lines.push(`${pad}}`);
  return lines;
}

function emitText(node: Extract<Node, { type: "text" }>, goVar: string, opacity: number, pad: string): string[] {
  const tmp = freshName("tmp");
  const lines: string[] = [];
  lines.push(`${pad}{`);
  lines.push(`${pad}  var ${tmp} = ${goVar}.AddComponent<TextMeshProUGUI>();`);
  lines.push(`${pad}  ${tmp}.text = ${csStringLiteral(node.content)};`);
  lines.push(`${pad}  ${tmp}.fontSize = ${node.fontSize}f * FontSizeScale;`);
  lines.push(`${pad}  ${tmp}.color = LwbColor(${csStringLiteral(node.color)}, ${opacity}f);`);
  lines.push(`${pad}  var f = LwbLoadFont(); if (f != null) ${tmp}.font = f;`);
  lines.push(
    `${pad}  ${tmp}.alignment = ${emitTmpAlignment(node.textAlign)};`,
  );
  lines.push(`${pad}  ${tmp}.raycastTarget = false;`);
  lines.push(`${pad}}`);
  return lines;
}

function emitTmpAlignment(a: string): string {
  switch (a) {
    case "left":
      return "TextAlignmentOptions.Left";
    case "center":
      return "TextAlignmentOptions.Center";
    case "right":
      return "TextAlignmentOptions.Right";
    default:
      return "TextAlignmentOptions.Left";
  }
}

function emitButton(
  node: Extract<Node, { type: "button" }>,
  goVar: string,
  opacity: number,
  pad: string,
): string[] {
  const lines: string[] = [];
  lines.push(`${pad}{`);
  lines.push(`${pad}  var img = ${goVar}.AddComponent<Image>();`);
  const aid = node.background?.assetId;
  if (aid) {
    lines.push(`${pad}  var sp = LwbLoadSprite(${csStringLiteral(aid)});`);
    lines.push(`${pad}  if (sp != null) img.sprite = sp;`);
  }
  lines.push(`${pad}  img.color = LwbColor(${csStringLiteral(node.background?.tint ?? "#FFFFFF")}, ${opacity}f);`);
  lines.push(`${pad}  var btn = ${goVar}.AddComponent<Button>();`);
  lines.push(`${pad}  btn.targetGraphic = img;`);
  lines.push(`${pad}}`);
  const labelGo = freshName("labelGo");
  const labelRt = freshName("labelRt");
  const tmp = freshName("tmpL");
  lines.push(`${pad}var ${labelGo} = new GameObject("Label");`);
  lines.push(`${pad}${labelGo}.transform.SetParent(${goVar}.transform, false);`);
  lines.push(`${pad}var ${labelRt} = ${labelGo}.AddComponent<RectTransform>();`);
  lines.push(`${pad}LwbApplyRect(${labelRt}, 0f, 0f, ${node.width}f, ${node.height}f, new Vector2(0.5f, 0.5f));`);
  lines.push(`${pad}{`);
  lines.push(`${pad}  var ${tmp} = ${labelGo}.AddComponent<TextMeshProUGUI>();`);
  lines.push(`${pad}  ${tmp}.text = ${csStringLiteral(node.label.content)};`);
  lines.push(`${pad}  ${tmp}.fontSize = ${node.label.fontSize}f * FontSizeScale;`);
  lines.push(`${pad}  ${tmp}.color = LwbColor(${csStringLiteral(node.label.color)}, ${opacity}f);`);
  lines.push(`${pad}  var f = LwbLoadFont(); if (f != null) ${tmp}.font = f;`);
  lines.push(`${pad}  ${tmp}.alignment = ${emitTmpAlignment(node.label.textAlign)};`);
  lines.push(`${pad}  ${tmp}.raycastTarget = false;`);
  lines.push(`${pad}}`);
  return lines;
}

function emitSlider(
  node: Extract<Node, { type: "slider" }>,
  goVar: string,
  _rtVar: string,
  pad: string,
): string[] {
  const lines: string[] = [];
  const bg = freshName("sBg");
  const fillArea = freshName("fillArea");
  const fill = freshName("fillG");
  const handleArea = freshName("hArea");
  const handle = freshName("hG");
  lines.push(`${pad}{`);
  lines.push(`${pad}  var sl = ${goVar}.AddComponent<Slider>();`);
  lines.push(`${pad}  sl.direction = Slider.Direction.LeftToRight;`);
  lines.push(`${pad}  sl.minValue = 0f; sl.maxValue = 1f; sl.wholeNumbers = false;`);
  lines.push(`${pad}  sl.value = ${node.defaultValue}f;`);
  lines.push(`${pad}  var ${bg} = new GameObject("Background"); ${bg}.transform.SetParent(${goVar}.transform, false);`);
  lines.push(
    `${pad}  var ${bg}Rt = ${bg}.AddComponent<RectTransform>(); LwbApplyRect(${bg}Rt, 0f, 0f, ${node.width}f, ${node.height}f, new Vector2(0f, 1f));`,
  );
  lines.push(`${pad}  var ${bg}Img = ${bg}.AddComponent<Image>();`);
  lines.push(
    `${pad}  { var sp = LwbLoadSprite(${node.trackImage?.assetId ? csStringLiteral(node.trackImage.assetId) : "null"}); if (sp != null) ${bg}Img.sprite = sp; ${bg}Img.color = Color.white; }`,
  );
  lines.push(`${pad}  sl.targetGraphic = ${bg}Img;`);
  lines.push(`${pad}  var ${fillArea} = new GameObject("Fill Area"); ${fillArea}.transform.SetParent(${goVar}.transform, false);`);
  lines.push(
    `${pad}  var ${fillArea}Rt = ${fillArea}.AddComponent<RectTransform>(); LwbApplyRect(${fillArea}Rt, 0f, 0f, ${node.width}f, ${node.height}f, new Vector2(0f, 1f));`,
  );
  lines.push(`${pad}  var ${fill} = new GameObject("Fill"); ${fill}.transform.SetParent(${fillArea}.transform, false);`);
  lines.push(
    `${pad}  var ${fill}Rt = ${fill}.AddComponent<RectTransform>(); LwbApplyRect(${fill}Rt, 0f, 0f, ${node.width}f, ${node.height}f, new Vector2(0f, 1f));`,
  );
  lines.push(`${pad}  var ${fill}Img = ${fill}.AddComponent<Image>();`);
  lines.push(
    `${pad}  { var sp = LwbLoadSprite(${node.fillImage?.assetId ? csStringLiteral(node.fillImage.assetId) : "null"}); if (sp != null) ${fill}Img.sprite = sp; }`,
  );
  lines.push(`${pad}  sl.fillRect = ${fill}Rt;`);
  lines.push(`${pad}  var ${handleArea} = new GameObject("Handle Slide Area"); ${handleArea}.transform.SetParent(${goVar}.transform, false);`);
  lines.push(
    `${pad}  var ${handleArea}Rt = ${handleArea}.AddComponent<RectTransform>(); LwbApplyRect(${handleArea}Rt, 0f, 0f, ${node.width}f, ${node.height}f, new Vector2(0f, 1f));`,
  );
  lines.push(`${pad}  var ${handle} = new GameObject("Handle"); ${handle}.transform.SetParent(${handleArea}.transform, false);`);
  lines.push(
    `${pad}  var ${handle}Rt = ${handle}.AddComponent<RectTransform>(); LwbApplyRect(${handle}Rt, 0f, 0f, ${Math.min(32, node.width)}f, ${Math.min(32, node.height)}f, new Vector2(0.5f, 0.5f));`,
  );
  lines.push(`${pad}  var ${handle}Img = ${handle}.AddComponent<Image>();`);
  lines.push(
    `${pad}  { var sp = LwbLoadSprite(${node.thumbImage?.assetId ? csStringLiteral(node.thumbImage.assetId) : "null"}); if (sp != null) ${handle}Img.sprite = sp; }`,
  );
  lines.push(`${pad}  sl.handleRect = ${handle}Rt;`);
  lines.push(`${pad}}`);
  return lines;
}

function emitToggle(
  node: Extract<Node, { type: "toggle" }>,
  goVar: string,
  _rtVar: string,
  opacity: number,
  pad: string,
): string[] {
  const lines: string[] = [];
  const bgGo = freshName("tBg");
  const ckGo = freshName("tCk");
  const labGo = freshName("tLab");
  lines.push(`${pad}{`);
  lines.push(`${pad}  var tg = ${goVar}.AddComponent<Toggle>();`);
  lines.push(`${pad}  tg.isOn = ${node.defaultOn ? "true" : "false"};`);
  lines.push(`${pad}  var ${bgGo} = new GameObject("Background"); ${bgGo}.transform.SetParent(${goVar}.transform, false);`);
  lines.push(
    `${pad}  var ${bgGo}Rt = ${bgGo}.AddComponent<RectTransform>(); LwbApplyRect(${bgGo}Rt, 0f, 0f, ${node.width * 0.4}f, ${node.height}f, new Vector2(0f, 1f));`,
  );
  lines.push(`${pad}  var ${bgGo}Img = ${bgGo}.AddComponent<Image>();`);
  lines.push(
    `${pad}  { var sp = LwbLoadSprite(${node.background?.assetId ? csStringLiteral(node.background.assetId) : "null"}); if (sp != null) ${bgGo}Img.sprite = sp; }`,
  );
  lines.push(`${pad}  tg.graphic = ${bgGo}Img;`);
  lines.push(`${pad}  var ${ckGo} = new GameObject("Checkmark"); ${ckGo}.transform.SetParent(${bgGo}.transform, false);`);
  lines.push(
    `${pad}  var ${ckGo}Rt = ${ckGo}.AddComponent<RectTransform>(); LwbApplyRect(${ckGo}Rt, 0f, 0f, ${node.width * 0.35}f, ${node.height * 0.85}f, new Vector2(0.5f, 0.5f));`,
  );
  lines.push(`${pad}  var ${ckGo}Img = ${ckGo}.AddComponent<Image>();`);
  lines.push(
    `${pad}  { var sp = LwbLoadSprite(${node.checkmark?.assetId ? csStringLiteral(node.checkmark.assetId) : "null"}); if (sp != null) ${ckGo}Img.sprite = sp; ${ckGo}Img.color = Color.white; }`,
  );
  lines.push(`${pad}  tg.graphic = ${ckGo}Img;`);
  lines.push(`${pad}  tg.targetGraphic = ${bgGo}Img;`);
  lines.push(`${pad}}`);
  lines.push(`${pad}var ${labGo} = new GameObject("Label"); ${labGo}.transform.SetParent(${goVar}.transform, false);`);
  lines.push(
    `${pad}var ${labGo}Rt = ${labGo}.AddComponent<RectTransform>(); LwbApplyRect(${labGo}Rt, ${node.width * 0.42}f, 0f, ${node.width * 0.55}f, ${node.height}f, new Vector2(0f, 1f));`,
  );
  const tmp = freshName("tTmp");
  lines.push(`${pad}{ var ${tmp} = ${labGo}.AddComponent<TextMeshProUGUI>();`);
  lines.push(`${pad}  ${tmp}.text = ${csStringLiteral(node.label.content)};`);
  lines.push(`${pad}  ${tmp}.fontSize = ${node.label.fontSize}f * FontSizeScale;`);
  lines.push(`${pad}  ${tmp}.color = LwbColor(${csStringLiteral(node.label.color)}, ${opacity}f);`);
  lines.push(`${pad}  var f = LwbLoadFont(); if (f != null) ${tmp}.font = f; }`);
  return lines;
}

function emitInputField(
  node: Extract<Node, { type: "inputField" }>,
  goVar: string,
  _rtVar: string,
  opacity: number,
  pad: string,
): string[] {
  const lines: string[] = [];
  lines.push(`${pad}{`);
  lines.push(`${pad}  var inp = ${goVar}.AddComponent<TMP_InputField>();`);
  lines.push(`${pad}  var bg = ${goVar}.GetComponent<Image>(); if (bg == null) bg = ${goVar}.AddComponent<Image>();`);
  lines.push(
    `${pad}  { var sp = LwbLoadSprite(${node.background?.assetId ? csStringLiteral(node.background.assetId) : "null"}); if (sp != null) bg.sprite = sp; }`,
  );
  lines.push(`${pad}  var textArea = new GameObject("Text Area"); textArea.transform.SetParent(${goVar}.transform, false);`);
  lines.push(
    `${pad}  var taRt = textArea.AddComponent<RectTransform>(); LwbApplyRect(taRt, 4f, 4f, ${node.width - 8}f, ${node.height - 8}f, new Vector2(0f, 1f));`,
  );
  lines.push(`${pad}  textArea.AddComponent<RectMask2D>();`);
  lines.push(`${pad}  var ph = new GameObject("Placeholder"); ph.transform.SetParent(textArea.transform, false);`);
  lines.push(
    `${pad}  var phRt = ph.AddComponent<RectTransform>(); LwbApplyRect(phRt, 0f, 0f, ${node.width - 8}f, ${node.height - 8}f, new Vector2(0f, 1f));`,
  );
  lines.push(`${pad}  var phTmp = ph.AddComponent<TextMeshProUGUI>(); phTmp.text = ${csStringLiteral(node.placeholder.content)};`);
  lines.push(`${pad}  phTmp.fontSize = ${node.placeholder.fontSize}f * FontSizeScale; phTmp.color = LwbColor(${csStringLiteral(node.placeholder.color)}, ${opacity * 0.5}f);`);
  lines.push(`${pad}  var tx = new GameObject("Text"); tx.transform.SetParent(textArea.transform, false);`);
  lines.push(
    `${pad}  var txRt = tx.AddComponent<RectTransform>(); LwbApplyRect(txRt, 0f, 0f, ${node.width - 8}f, ${node.height - 8}f, new Vector2(0f, 1f));`,
  );
  lines.push(`${pad}  var txTmp = tx.AddComponent<TextMeshProUGUI>(); txTmp.text = ${csStringLiteral(node.text.content)};`);
  lines.push(`${pad}  txTmp.fontSize = ${node.text.fontSize}f * FontSizeScale; txTmp.color = LwbColor(${csStringLiteral(node.text.color)}, ${opacity}f);`);
  lines.push(`${pad}  inp.textComponent = txTmp; inp.placeholder = phTmp; inp.textViewport = taRt;`);
  lines.push(`${pad}}`);
  return lines;
}
